PrimeiraAvaliacao/Controllers/TipoDeAssociacaoController.cs
using PrimeiraAvaliacao.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrimeiraAvaliacao.Controllers
{
    public class TipoDeAssociacaoController : Controller
    {


        private ApplicationDbContext _context;

        public TipoDeAssociacaoController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public IEnumerable<TipoDeAssociacao> GetTipoDeAssociacao()
        {

            /*return new List<TipoDeAssociacao>
            {
                new TipoDeAssociacao {Nome = "Mensal", Periodo = 1, Mensalidade = 123, Id = 1},
                new TipoDeAssociacao {Nome = "Anual", Periodo = 5, Mensalidade = 300, Id = 2},
                new TipoDeAssociacao {Nome = "Semanal", Periodo = 24, Mensalidade = 13, Id = 3}
            };*/
            IEnumerable<TipoDeAssociacao> tipos = _context.TipoDeAssociacao.ToList();
            return tipos;
        }


        public ActionResult Index()
        {
            return View(GetTipoDeAssociacao());
        }

        public ActionResult Details(int id)
        {
            var tipo = GetTipoDeAssociacao().SingleOrDefault(m => m.Id == id);

            if (tipo == null)
                return HttpNotFound();

            return View(tipo);

        }
    }
}

PrimeiraAvaliacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Primeira Prova", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Aluno", "Index", "Aluno")</li>
                    <li>@Html.ActionLink("Faixa", "Index", "Faixa")</li>
                    <li>@Html.ActionLink("Tipo de Associação", "Index", "TipoDeAssociacao")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>